org: steeng
app: aws-node-project
service: aws-node-project
frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1
  stage: dev 
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
